version: "3.8"
services:
  postgres_db:
    image: postgres:13.5
    container_name: demo_99_tech_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=demo_99_tech
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_db:
    driver: local
